### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by applejag** [swansontec/rfc4648.js#18]
Hello! We're depending on this project, but you seem to be missing a LICENSE file, making this project copyrighted.

Your `package.json` states you're using MIT license, but without a license text and copyright notice, this isn't enough.

Kind regards,
Kalle

**Comment by swansontec** [comment]
Ok, I think I fixed that in the repo. Do you need it to be published to NPM as well?

**Comment by applejag** [comment]
Please do, if it's not too much trouble :)

**Comment by swansontec** [comment]
Ok, v1.5.1 is up now.
